services:
  ros_dev:
    image: avra_humble_v3
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - USER_UID=1000
        - USER_GID=1000
    container_name: avra_v3
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - USER=ros
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - .:/home/ros/avra_ws
      - /dev:/dev
    stdin_open: true
    tty: true
    # Fail-safe: Forces sourcing even if .bashrc is bypassed
    command: >
      bash -c "source /opt/ros/humble/setup.bash && 
               tail -f /dev/null"
